apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: inovola
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
        - image: moustafayoussef/restaurant_webapp:0.2
          imagePullPolicy: Always
          name: webapp
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          envFrom:
          - configMapRef:
              name: rest-configmap
          - secretRef:
              name: rest-secret    
          readinessProbe:
              httpGet:
                      path: /monitoring/readiness
                      port: 5000     
          livenessProbe:
              initialDelaySeconds: 10    
              httpGet:
                      path: /monitoring/liveness
                      port: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
