apiVersion: v1
kind: Service
metadata:
  name: {{ include "restaurant-app.fullname" . }}
  labels:
    {{- include "restaurant-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: test-app
  selector:
    {{- include "restaurant-app.selectorLabels" . | nindent 4 }}
