apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: cicd-rolebinding
  namespace: restaurant-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cicd
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: cicd-539@third-wharf-422315-u9.iam.gserviceaccount.com